SET IDENTITY_INSERT [dbo].[flower] ON
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (1, N'Balsam', CAST(12.00 AS Decimal(10, 2)), N'Pink', N'2023-12-13', N'balsam.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (2, N'Chost', CAST(12.50 AS Decimal(10, 2)), N'Pink', N'2023-11-13', N'chost.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (3, N'Crape', CAST(12.50 AS Decimal(10, 2)), N'White', N'2023-12-12', N'crape.jgp')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (4, N'Cross', CAST(11.50 AS Decimal(10, 2)), N'Orange', N'2023-12-09', N'cross.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (5, N'Daisy', CAST(11.00 AS Decimal(10, 2)), N'White', N'2023-12-07', N'daisy.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (6, N'Flax', CAST(12.50 AS Decimal(10, 2)), N'blue', N'2023-03-29', N'flax.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (7, N'Frani', CAST(11.00 AS Decimal(10, 2)), N'White', N'2023-12-07', N'frani.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (8, N'Jasmine', CAST(9.00 AS Decimal(10, 2)), N'White', N'2023-12-12', N'jasmine.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (9, N'Lavender', CAST(8.50 AS Decimal(10, 2)), N'Purple', N'2023-12-17', N'lavender.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (10, N'Lotus', CAST(5.00 AS Decimal(10, 2)), N'Purple', N'2023-12-23', N'lotus.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (11, N'Magnolia', CAST(13.50 AS Decimal(10, 2)), N'White', N'2023-12-29', N'magnoila.jgp')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (12, N'Marigold', CAST(14.00 AS Decimal(10, 2)), N'Yellow', N'2023-12-25', N'marigold.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (13, N'Night', CAST(15.00 AS Decimal(10, 2)), N'White', N'2023-12-26', N'night.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (14, N'Night', CAST(15.00 AS Decimal(10, 2)), N'White', N'2023-12-26', N'night.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (15, N'Rose', CAST(16.00 AS Decimal(10, 2)), N'Red', N'2023-12-03', N'rose.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (16, N'Shower', CAST(9.00 AS Decimal(10, 2)), N'Yellow', N'2023-12-03', N'shower.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (17, N'Pot', CAST(5.00 AS Decimal(10, 2)), N'White', N'2023-12-06', N'pot.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (18, N'Sunflower', CAST(6.00 AS Decimal(10, 2)), N'Yellow', N'2023-12-07', N'sunflower.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (19, N'Lilly', CAST(7.00 AS Decimal(10, 2)), N'White', N'2023-12-11', N'lilly.jpg')
INSERT INTO [dbo].[flower] ([FlowerID], [FlowerName], [FlowerPrice], [FlowerColour], [FlowerExpiryDate], [FlowerImg]) VALUES (20, N'Orchid', CAST(8.00 AS Decimal(10, 2)), N'Pink', N'2023-12-29', N'orchid.jpg')
SET IDENTITY_INSERT [dbo].[flower] OFF
